create table employee (emp_id int auto_increment, name char (10), salary int (10), primary key(emp_id));
insert into employee(name, salary) values ('Anjali',55000);
insert into employee(name, salary) values ('Gyani',80000);
insert into employee(name, salary) values ('Pradeep',55000);
insert into employee(name, salary) values ('Monica',60000);
insert into employee(name, salary) values ('Deepak',90000);
select distinct salary from employee;
select * from employee where name = 'Monica' or (emp_id=001 and salary = 55000);
select * from employee order by name;
update employee set salary = salary*2 where emp_id>3;
delete from employee where emp_id = 5;
select * from employee limit 3;
select * from employee where name not like '%eep%';
select * from employee where name like '_r_d__p';
select * from employee where name like '[ABD]%';
select * from employee where salary in (55000,80000);
select * from employee where salary between 57000 and 130000;
select * from employee where name between 'A' and 'J';
create table empbackup (emp_id int (10), name char (10), salary int (10), primary key(emp_id));
select * into empbackup from employee;
select * from empbackup;
select * into backup2 from employee where 1=0;